logging:
  level: INFO
  loggers:
    "org.col": DEBUG
  appenders:
    - type: console
db:
  # set host to null to use the embedded pg server
  host: ${db.host}
  port: 5432
  database: ${db.database}
  user: ${db.user}
  password: ${db.password}
auth:
  signingKey: 3254e6rftgbzg6tz7
  gbifSecret: 123456789
