server:
  requestLog:
    type: logback-access
    appenders:
      - type: console
        timeZone: UTC
logging:
  level: INFO
  loggers:
    "org.apache.http": WARN
    "org.eclipse.jetty.servlet": WARN
    "life.catalogue": INFO
    "life.catalogue.db.mapper": DEBUG
    "life.catalogue.db.legacy": INFO
  appenders:
    - type: console
      timeZone: UTC
db:
  # set host to null to use the embedded pg server
  host: ${db.host}
  port: ${db.port}
  database: ${db.database}
  user: ${db.user}
  password: ${db.password}
normalizer:
  scratchDir: /tmp/col/scratch
  archiveDir: /tmp/col/archives
client:
  timeout: 10000ms
  connectionTimeout: 5000ms
  timeToLive: 1h
  cookiesEnabled: false
  maxConnections: 64
  maxConnectionsPerRoute: 16
  keepAlive: 0ms
  retries: 1
es:
  hosts: ${es.hosts}
  ports: ${es.ports}
  nameUsage:
    name: ${es.index}
    numShards: 1
    numReplicas: 0
auth:
  type: map
  users:
    - username: user
      password: test
    - username: editor
      password: test
      role: editor
      datasets: [1,2,3,1000]
    - username: admin
      password: test
      role: admin
jwtKey: 3254e6rftgbzg6tz73254e6rftgbzg6tz73254e6rftgbzg6tz7
img:
  repo: ${img.repo}
  archive: ${img.repo}/archive
cors:
  headers: "Authorization, Content-Type, Accept-Language, X-Requested-With, User-Agent, Referer"
namesIndexFile: /tmp/col/nidx
metricsRepo: /tmp/col/metrics
