version: '1.0 beta'
title: COL ChecklistBank API
description: 'This is the Catalogue of Life ChecklistBank API that drives all of [CoL ChecklistBank](http://data.catalogue.life).
The API is still in active development and not finalized, small changes are still expected to take place before the release of version 1.0.

For questions, suggestions and discussion please subscribe to our [API mailing list](https://lists.gbif.org/mailman/listinfo/col-users)
, which we also use to inform about planned downtimes and breaking API changes.

Alternatively you are welcome to [file a bug report or feature request](https://github.com/CatalogueOfLife/backend/issues/new) in our github repository.
'
contact:
  email: mdoering@gbif.org

https://lists.gbif:org/mailman/listinfo/col-users