version: '1.0 alpha'
title: Catalogue of Life Clearinghouse API
description: 'This is the Catalogue of Life API that drives all of the [CoL Clearinghouse UI](http://data.catalogue.life).
The API is still in development and not finalized, small changes are still expected to take place before the release of version 1.0.

If the documentation here is too sparse please also consult the [previous but heavily outdated API docs](https://catalogueoflife.github.io/general/api/api.html).
These are much richer and contain real work examples, but we just cannot keep up with the documentation manually.

Use with caution!
'
contact:
  email: mdoering@gbif.org
